bccAlertRecipient = "care.force5+bcc@gmail.com"
grails {
    mail {
        fromEmailAddress = "CARE Admin <admin@dev.care.net>"
        host = "qa.care.net"
        port = "25"
        username = "username"
        password = "password"
        defaultEmail {
            from = "CARE Admin <admin@dev.care.net>"
        }
    }
}
snmpServerUrl = "udp:qa3.intelligrape.net/162"
sendEmail = "false"
sponsorExpirationJobRepeatInterval = "10000"
revokeAccessJobRepeatInterval = "1000000"
emailDomain = "@gmail.com"
praCertificationId = "3"
contractorPraCertificationId = "3"
isEmployeeEditable = "false"
isContractorEditable = "false"
rssFeedUrl = "http://www.forbes.com/news/index.xml"
snmpOid = "1.3.6.1.2.1.2.1"
contractorApprovalWorkflow = "flows/access-request-contractor.rf"
contractorRevocationWorkflow = "flows/revoke-request-contractor.rf"
contractorTerminationWorkflow = "flows/terminate-request.rf"
employeeApprovalOldWorkflow = "flows/old-access-request.rf"
employeeApprovalWorkflow = "flows/access-request.rf"
provisionerDeprovisionerTasksOnRoleUpdateWorkflow = "flows/provisioner-deprovisioner-tasks-approval.rf"
employeeRevocationWorkflow = "flows/revoke-request.rf"
employeeTerminationWorkflow = "flows/terminate-request.rf"
certificationExpirationNotificationWorkflow = "flows/certification-expiration-notification.rf"
addEntitlementPolicyWorkflow = "flows/add-entitlement-policy.rf"
updateEntitlementPolicyWorkflow = "flows/update-entitlement-policy.rf"
accessVerificationWorkflow = "flows/access-verification-v2.rf"
accessGrantedByFeedWorkflow = "flows/access-granted-by-feed.rf"
accessRevokedByFeedWorkflow = "flows/access-revoked-by-feed.rf"
hrInfoMandatoryFields = "pernr, slid"
accessVerificationCronTrigger = "0 0 0 1 1 ? 2050"
certificationExpirationNotificationCronTrigger = "0 0 0 1 1 ? 2050"
revokeAccessCronTrigger = "0 0 0 1 1 ? 2050"
sponsorExpirationCronTrigger = "0 0 0 1 1 ? 2050"
courseFeedCronTrigger = "0 0 0 1 1 ? 2050"
praFeedCronTrigger = "0 0 0 1 1 ? 2050"
employeePraFeedCronTrigger = "0 0 0 1 1 ? 2050"
hrInfoFeedCronTrigger = "0 0 0 1 1 ? 2050"
escalationCronTrigger = "0 0 0 1 1 ? 2050"
activeWorkerCronTrigger = "0 0 0 1 1 ? 2050"
createApsTaskForAccessVerificationTimeOutCronTrigger = "0 0 0 1 1 ? 2050"
autoArchiveCompletedWorkflowTaskCronTrigger = "0 0 0 1 1 ? 2050"
certificationCompletionTimeOutCronTrigger = "0 0 0 1 1 ? 2050"
contractorHrInfoFeedCronTrigger = "0 0 0 1 1 ? 2050"
contractorCourseFeedCronTrigger = "0 0 0 1 1 ? 2050"
contractorPraFeedCronTrigger = "0 0 0 1 1 ? 2050"
workerCertificationArchiveCronTrigger = "0 0/5 * * * ? *"
superAdminSlids = "admin, topuser1"
top {
    activeDirectory {
        simulate = "true"
        ldapHost = "ldap://173.162.65.181"
        searchBase = "dc=f5lab,dc=local"
        securityAuthentication = "simple"
        domain = "f5lab.local"
    }
}
webServiceSlids = "admin, topuser1"
defaultSecurityGroup = "DEFAULT"
accessVerificationWaitPeriodInHours = "144"
defaultSupervisorSlid = "supslid-8"
superAdminSlids = "admin, topuser1"
complianceDashboardFileGenerationCronTrigger = "0 0/5 * * * ? *"
complianceDashboardFileFolderLocation = "/tmp"
complianceDashboardFileGenerationLastRunTime = "0"
revokeOnMissingCertificationsCronTrigger = "0 0 0 1 1 ? 2050"
daysPriorToKickOffWorkflowInMissingCertificationRevocation = "7"
autoArchiveCompletedWorkflowTaskDaysInterval = "30"
certificationCompletionTimeOutInDays = '2'
showCertificationsInPublicAccessRequest = 'true'
reloadPublicDashboardTimeInterval = "900000"
showContractorDashboard = 'true'
EAMSUrl = 'http://inapp.fpl.com:8006/AlertEnterprise'
defaultOrgTreeWorkerListView = "true"
cipEntitlementPolicies = "Physical CIP, Cyber CIP"
defaultSizeOfListView = "10"
runDatabaseFeedForEmployeeCourse = "true"
runDatabaseFeedForEmployeePra = "true"
runDatabaseFeedForContractorHrInfo = "false"
runDatabaseFeedForContractorCourse = "false"
runDatabaseFeedForContractorPra = "false"