truncate table asynchronous_mail_attachment;
truncate table asynchronous_mail_message_bcc;
truncate table asynchronous_mail_message_cc;
truncate table asynchronous_mail_message_headers;
truncate table asynchronous_mail_message_to;
truncate table asynchronous_mail_message;

